---
functional:
  - Пользователь может зарегистрироваться и войти в систему с помощью электронной почты и пароля или через аккаунт GitHub
  - При создании игры, пользователь должен иметь возможность настроить игру по критериям (тип, сложность, время и т.п.)
  - У пользователя должна быть возможность зайти в игру как зритель
  - У игрока должна быть возможность прервать игру в любой момент
  - У пользователей должна быть возможность общаться в чате во время игры
  - У пользователя должна быть возможность посмотреть актуальную статистику и активность у себя в профиле
  - У пользователя должна быть возможность просматривать информацию о предыдущих завершенных играх у себя в профиле
non-functional:
  - Интерфейс должен быть интуитивно понятен
  - Сайт должен выдерживать большую нагрузку на сервер
  - Сайт должен быть защищен от XSS и других атак
  - Сайт должен быть адаптивен
  - Сайт должен быть кроссбраузерным
implicit:
  - Система должна стимулировать пользователей к участию
  - Рейтинговая система должна быть прозрачной и понятной
  - Платформа должна быть визуально приятной
  - Обучение должно быть понятным пользователю
